language: android

android:
  components:
    - build-tools-29.0.2
    - android-29
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle